<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Comment Model
 * Generated by EasyAPP CLI from table: comments
 */
class Comment extends Orm {

    protected static $table = 'comments';
    protected static $softDelete = true;
    protected static $timestamps = true;
    
    protected static $fillable = [
        'post_id',
        'user_id',
        'parent_id',
        'content',
        'status',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'post_id' => 'int',
        'user_id' => 'int',
        'parent_id' => 'int',
    ];
    
    // ATTRIBUTE LABELS
    
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'post_id' => 'Post ID',
            'user_id' => 'User ID',
            'parent_id' => 'Parent ID',
            'content' => 'Content',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }
    
    // VALIDATION
    
    public function rules() {
        return [
             ['post_id', 'required|integer'],
             ['user_id', 'required|integer'],
             ['parent_id', 'optional|integer'],
             ['content', 'required|string'],
             ['status', 'optional|in:pending,approved,rejected'],
         ];
     }
    
    
    // RELATIONSHIPS
    
    public function post() {
        return $this->belongsTo(Post::class, 'post_id');
    }
    
    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    public function comment() {
        return $this->belongsTo(Comment::class, 'parent_id');
    }
    
}
