<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Comment Model
 * Generated by EasyAPP CLI from table: comments
 */
class Comment extends Orm {

    protected static $table = 'comments';
    protected static $softDelete = true;
    protected static $timestamps = true;
    
    protected static $fillable = [
        'post_id',
        'user_id',
        'parent_id',
        'content',
        'status',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'post_id' => 'int',
        'user_id' => 'int',
        'parent_id' => 'int',
    ];
    
    // ==================== VALIDATION ====================
    
    /**
     * Validation rules
     * Auto-generated from table schema
     */
    public function rules() {
        return [
            ['post_id', 'required|integer'],
            ['user_id', 'required|integer'],
            ['parent_id', 'optional|integer'],
            ['content', 'required|string'],
            ['status', 'optional|in:pending,approved,rejected'],
        ];
    }
    
    
    // ==================== RELATIONSHIPS ====================
    
    /**
     * Get the Post that this Comment belongs to
     */
    public function post() {
        return $this->belongsTo(Post::class, 'post_id');
    }
    
    /**
     * Get the User that this Comment belongs to
     */
    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    /**
     * Get the Comment that this Comment belongs to
     */
    public function comment() {
        return $this->belongsTo(Comment::class, 'parent_id');
    }
    
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
}
