<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * FrameworkMigration Model
 * Generated by EasyAPP CLI from table: framework_migrations
 */
class FrameworkMigration extends Orm {

    protected static $table = 'framework_migrations';
    protected static $timestamps = false;
    
    protected static $fillable = [
        'version',
        'class_name',
        'description',
        'applied_at',
        'execution_time',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'applied_at' => 'datetime',
        'execution_time' => 'int',
    ];
    
    // ATTRIBUTE LABELS
    
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'version' => 'Version',
            'class_name' => 'Class Name',
            'description' => 'Description',
            'applied_at' => 'Applied At',
            'execution_time' => 'Execution Time',
        ];
    }
    
    // VALIDATION
    
    public function rules() {
        return [
             ['version', 'required|string|maxLength:10'],
             ['class_name', 'required|string|maxLength:255|minLength:2'],
             ['description', 'optional|string'],
             ['applied_at', 'required|datetime'],
             ['execution_time', 'optional|integer'],
         ];
     }
    
}
