<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * FrameworkMigration Model
 * Generated by EasyAPP CLI from table: framework_migrations
 */
class FrameworkMigration extends Orm {

    protected static $table = 'framework_migrations';
    protected static $timestamps = false;
    
    protected static $fillable = [
        'version',
        'class_name',
        'description',
        'applied_at',
        'execution_time',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'applied_at' => 'datetime',
        'execution_time' => 'int',
    ];
    
    // ==================== VALIDATION ====================
    
    /**
     * Validation rules
     * Auto-generated from table schema
     * 
     * Uncomment to enable automatic validation on save/create
     */
    public function rules() {
        return [
            ['version', 'required|string|maxLength:10'],
            ['class_name', 'required|string|maxLength:255|minLength:2'],
            ['description', 'optional|string'],
            ['applied_at', 'required|datetime'],
            ['execution_time', 'optional|integer'],
        ];
    }
    
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
}
