<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Post Model
 * Generated by EasyAPP CLI from table: posts
 */
class Post extends Orm {

    protected static $table = 'posts';
    protected static $softDelete = true;
    protected static $timestamps = true;
    
    protected static $fillable = [
        'user_id',
        'title',
        'slug',
        'content',
        'status',
        'views',
        'published_at',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'user_id' => 'int',
        'views' => 'int',
        'published_at' => 'datetime',
    ];
    
    // ATTRIBUTE LABELS
    
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'title' => 'Title',
            'slug' => 'Slug',
            'content' => 'Content',
            'status' => 'Status',
            'views' => 'Views',
            'published_at' => 'Published At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }
    
    // VALIDATION
    
    public function rules() {
        return [
             ['user_id', 'required|integer'],
             ['title', 'required|string|maxLength:255'],
             ['slug', 'required|string|maxLength:255'],
             ['content', 'required|string'],
             ['status', 'optional|in:draft,published,archived'],
             ['views', 'optional|integer'],
             ['published_at', 'optional|datetime'],
         ];
     }
    
    
    // RELATIONSHIPS
    
    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
}
