<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * PostTag Model
 * Generated by EasyAPP CLI from table: post_tag
 */
class PostTag extends Orm {

    protected static $table = 'post_tag';
    protected static $timestamps = false;
    
    protected static $fillable = [
        'post_id',
        'tag_id',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'post_id' => 'int',
        'tag_id' => 'int',
    ];
    
    // ==================== VALIDATION ====================
    
    /**
     * Validation rules
     * Auto-generated from table schema
     * 
     * Uncomment to enable automatic validation on save/create
     */
    public function rules() {
        return [
            ['post_id', 'required|integer'],
            ['tag_id', 'required|integer'],
        ];
    }
    
    
    // ==================== RELATIONSHIPS ====================
    
    /**
     * Get the Post that this PostTag belongs to
     */
    public function post() {
        return $this->belongsTo(Post::class, 'post_id');
    }
    
    /**
     * Get the Tag that this PostTag belongs to
     */
    public function tag() {
        return $this->belongsTo(Tag::class, 'tag_id');
    }
    
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
}
