<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Post Model
 * Generated by EasyAPP CLI from table: posts
 */
class Post extends Orm {

    protected static $table = 'posts';
    protected static $softDelete = true;
    protected static $timestamps = true;
    
    protected static $fillable = [
        'user_id',
        'title',
        'slug',
        'content',
        'status',
        'views',
        'published_at',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'user_id' => 'int',
        'views' => 'int',
        'published_at' => 'datetime',
    ];
    
    // ==================== RELATIONSHIPS ====================
    
    /**
     * Get the User that this Post belongs to
     */
    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
    // ==================== VALIDATION ====================
    
    /**
     * Validation rules
     * Auto-generated from table schema
     * 
     * Note: Validation is optional. Uncomment to enable.
     */
    public function rules() {
        return [
            ['user_id', 'required|integer'],
            ['title', 'required|string|maxLength:255'],
            ['slug', 'required|string|maxLength:255'],
            ['content', 'required|string'],
            ['status', 'optional|in:draft,published,archived'],
            ['views', 'optional|integer'],
            ['published_at', 'optional|datetime'],
        ];
    }
    
}
