<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * PostTag Model
 * Generated by EasyAPP CLI from table: post_tag
 */
class PostTag extends Orm {

    protected static $table = 'post_tag';
    protected static $timestamps = false;
    
    protected static $fillable = [
        'post_id',
        'tag_id',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'post_id' => 'int',
        'tag_id' => 'int',
    ];
    
    // ATTRIBUTE LABELS 
    
    public function attributeLabels() {
        return [
            'post_id' => 'Post ID',
            'tag_id' => 'Tag ID',
        ];
    }
    
    // VALIDATION 
    
    public function rules() {
        return [
             ['post_id', 'required|integer'],
             ['tag_id', 'required|integer'],
         ];
     }
    
    
    // RELATIONSHIPS 
    
    public function post() {
        return $this->belongsTo(Post::class, 'post_id');
    }
    
    public function tag() {
        return $this->belongsTo(Tag::class, 'tag_id');
    }
    
}
