<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Profile Model
 * Generated by EasyAPP CLI from table: profiles
 */
class Profile extends Orm {

    protected static $table = 'profiles';
    protected static $timestamps = true;
    
    protected static $fillable = [
        'user_id',
        'bio',
        'avatar',
        'website',
        'location',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'user_id' => 'int',
    ];
    
    // ATTRIBUTE LABELS
    
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'bio' => 'Bio',
            'avatar' => 'Avatar',
            'website' => 'Website',
            'location' => 'Location',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    
    // VALIDATION
    
    public function rules() {
        return [
             ['user_id', 'required|integer'],
             ['bio', 'optional|string'],
             ['avatar', 'optional|string|maxLength:255'],
             ['website', 'optional|string|maxLength:255|url'],
             ['location', 'optional|string|maxLength:255'],
         ];
     }
    
    
    // RELATIONSHIPS
    
    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
}
