<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Profile Model
 * Generated by EasyAPP CLI from table: profiles
 */
class Profile extends Orm {

    protected static $table = 'profiles';
    protected static $timestamps = true;
    
    protected static $fillable = [
        'user_id',
        'bio',
        'avatar',
        'website',
        'location',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'user_id' => 'int',
    ];
    
    // ==================== VALIDATION ====================
    
    /**
     * Validation rules
     * Auto-generated from table schema
     * 
     * Uncomment to enable automatic validation on save/create
     */
    public function rules() {
        return [
            ['user_id', 'required|integer'],
            ['bio', 'optional|string'],
            ['avatar', 'optional|string|maxLength:255'],
            ['website', 'optional|string|maxLength:255|url'],
            ['location', 'optional|string|maxLength:255'],
        ];
    }
    
    
    // ==================== RELATIONSHIPS ====================
    
    /**
     * Get the User that this Profile belongs to
     */
    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
}
