<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Role Model
 * Generated by EasyAPP CLI from table: roles
 */
class Role extends Orm {

    protected static $table = 'roles';
    protected static $timestamps = true;
    
    protected static $fillable = [
        'name',
        'description',
    ];
    
    
    // ATTRIBUTE LABELS 
    
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    
    // VALIDATION 
    
    public function rules() {
        return [
             ['name', 'required|string|maxLength:100|minLength:2'],
             ['description', 'optional|string|maxLength:255'],
         ];
     }
    
}
