<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * RoleUser Model
 * Generated by EasyAPP CLI from table: role_user
 */
class RoleUser extends Orm {

    protected static $table = 'role_user';
    protected static $timestamps = false;
    
    protected static $fillable = [
        'user_id',
        'role_id',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'user_id' => 'int',
        'role_id' => 'int',
    ];
    
    // ATTRIBUTE LABELS 
    
    public function attributeLabels() {
        return [
            'user_id' => 'User ID',
            'role_id' => 'Role ID',
        ];
    }
    
    // VALIDATION 
    
    public function rules() {
        return [
             ['user_id', 'required|integer'],
             ['role_id', 'required|integer'],
         ];
     }
    
    
    // RELATIONSHIPS 
    
    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    public function role() {
        return $this->belongsTo(Role::class, 'role_id');
    }
    
}
