<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Role Model
 * Generated by EasyAPP CLI from table: roles
 */
class Role extends Orm {

    protected static $table = 'roles';
    protected static $timestamps = true;
    
    protected static $fillable = [
        'name',
        'description',
    ];
    
    
    // ==================== VALIDATION ====================
    
    /**
     * Validation rules
     * Auto-generated from table schema
     * 
     * Uncomment to enable automatic validation on save/create
     */
    public function rules() {
        return [
            ['name', 'required|string|maxLength:100|minLength:2'],
            ['description', 'optional|string|maxLength:255'],
        ];
    }
    
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
}
