<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * RoleUser Model
 * Generated by EasyAPP CLI from table: role_user
 */
class RoleUser extends Orm {

    protected static $table = 'role_user';
    protected static $timestamps = false;
    
    protected static $fillable = [
        'user_id',
        'role_id',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'user_id' => 'int',
        'role_id' => 'int',
    ];
    
    // ==================== VALIDATION ====================
    
    /**
     * Validation rules
     * Auto-generated from table schema
     * 
     * Uncomment to enable automatic validation on save/create
     */
    public function rules() {
        return [
            ['user_id', 'required|integer'],
            ['role_id', 'required|integer'],
        ];
    }
    
    
    // ==================== RELATIONSHIPS ====================
    
    /**
     * Get the User that this RoleUser belongs to
     */
    public function user() {
        return $this->belongsTo(User::class, 'user_id');
    }
    
    /**
     * Get the Role that this RoleUser belongs to
     */
    public function role() {
        return $this->belongsTo(Role::class, 'role_id');
    }
    
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
}
