<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * Tag Model
 * Generated by EasyAPP CLI from table: tags
 */
class Tag extends Orm {

    protected static $table = 'tags';
    protected static $timestamps = true;
    
    protected static $fillable = [
        'name',
        'slug',
    ];
    
    
    // ATTRIBUTE LABELS
    
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'slug' => 'Slug',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    
    // VALIDATION
    
    public function rules() {
        return [
             ['name', 'required|string|maxLength:100|minLength:2'],
             ['slug', 'required|string|maxLength:100'],
         ];
     }
    
}
