<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * User Model
 * Generated by EasyAPP CLI from table: users
 */
class User extends Orm {

    protected static $table = 'users';
    protected static $softDelete = true;
    protected static $timestamps = true;
    
    protected static $fillable = [
        'name',
        'email',
        'password',
        'role',
        'status',
    ];
    
    protected static $hidden = [
        'password',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'status' => 'int',
    ];

    public function getFullNameAttribute() {
        return $this->name; // Example accessor
    }

    public function setPasswordAttribute($value) {
        $this->attributes['password'] = password_hash($value, PASSWORD_BCRYPT); // Example mutator
    }

    public function changeStatus($newStatus) {
        $this->status = $newStatus;
        $this->save();
    }
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
}
