<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * User Model
 * Generated by EasyAPP CLI from table: users
 */
class User extends Orm {

    protected static $table = 'users';
    protected static $softDelete = true;
    protected static $timestamps = true;
    
    protected static $fillable = [
        'name',
        'email',
        'password',
        'role',
        'status',
    ];
    
    protected static $hidden = [
        'password',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'status' => 'int',
    ];
    
    // ATTRIBUTE LABELS 
    
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
            'password' => 'Password',
            'role' => 'Role',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }
    
    // VALIDATION 
    
    public function rules() {
        return [
             ['name', 'required|string|maxLength:255|minLength:2'],
             ['email', 'required|string|maxLength:255|email'],
             ['password', 'required|string|maxLength:255'],
             ['role', 'optional|in:user,admin,moderator'],
             ['status', 'optional|integer'],
         ];
     }

     // RELATIONSHIPS

     public function posts() {
        return $this->hasMany(Post::class, 'user_id');
    }
    
}
