<?php

namespace App\Model;

use System\Framework\Orm;

/**
 * User Model
 * Generated by EasyAPP CLI from table: users
 */
class User extends Orm {

    protected static $table = 'users';
    protected static $softDelete = true;
    protected static $timestamps = true;
    
    protected static $fillable = [
        'name',
        'email',
        'password',
        'role',
        'status',
    ];
    
    protected static $hidden = [
        'password',
    ];
    
    protected static $casts = [
        'id' => 'int',
        'status' => 'int',
    ];
    
    // ==================== VALIDATION ====================
    
    /**
     * Validation rules
     * Auto-generated from table schema
     * 
     * Note: Validation is optional. Uncomment to enable.
     * For password, we allow up to 255 chars to accommodate bcrypt hashes (60 chars)
     */
    public function rules() {
        return [
            ['name', 'required|string|maxLength:255|minLength:2'],
            ['email', 'required|string|maxLength:255|email'],
            // Password is optional for updates (when not changing password)
            // For creates, it should be present
            ['password', 'optional|string|maxLength:255'],
            ['role', 'optional|in:user,admin,moderator'],
            ['status', 'optional|integer'],
        ];
    }
    
    // ==================== RELATIONSHIPS ====================
    
    /**
     * Get all posts for this user
     */
    public function posts() {
        return $this->hasMany(\App\Model\Post::class, 'user_id');
    }
    
    // Example relationships:
    // public function posts() {
    //     return $this->hasMany(Post::class);
    // }
    
}
